#!/bin/bash

# Author: Evan BITIC
# Date: 29/06/2022

# Tools that allow to get informations (Hostname, IP Address, Status) on a docker container.

# Get all containers names
containers=`docker ps -a --format '{{.Names}}'`

# Function who get informations with docker inspect command and jq for parse the return.  
getContainerInfo() {
	for ct in $containers; do
		if [ "$ct" = "$container" ]; then
			docker inspect $container | jq '.[0] | {"Hostname" : .Config.Hostname, "IP" : .NetworkSettings.Networks.bridge.IPAddress,"Status": .State.Status }'
			exit 0 
		fi
	done
	echo "Container not found"
} 

# If no arguments, exit with error.
if [ $# -eq 0 ]; then
	exit 1
	#while true
	#do
		#read -p "Container name: " container
		#getContainerInfo
	#done

# Else, we take the first argument as container name
else
	container=$1
	getContainerInfo	
fi
